### ISSUE TITLE
Мета: идеи для уроков

### ISSUE THREAD

**Issue by MasterGroosha** [MasterGroosha/telegram-tutorial-2#2]
~~Можно рассказать про content_types.ANY, про встроенный эскейпинг HTML и Markdown~~

https://mastergroosha.github.io/telegram-tutorial-2/lesson_02/

**Comment by MasterGroosha** [comment]
Идея: https://gist.github.com/MasterGroosha/b3c45b8b87c857db7d88c193c6643ba8
Рассказать про работу в качестве ещё одного API совместно с ботом.

**Comment by masterbpro** [comment]
Рассказать про встроенный FSM в aiogram

**Comment by MasterGroosha** [comment]
Закрываю. Идея с Roadmap может быть воскрешена после перехода на aiogram 3.x
