### ISSUE TITLE
Обратится к методам бота из хендлера

### ISSUE THREAD

**Issue by ANAT01** [MasterGroosha/telegram-tutorial-2#5]
Извените за нубство, некак не пойму, как обратится к методам aiogram.Bot из функций хендлеров

Например в `handlers/common.py`

```python

async def cmd_start(message: types.Message):
    await message.answer(
        "Выберите, что хотите заказать: напитки (/drinks) или блюда (/food).",
        reply_markup=types.ReplyKeyboardRemove()
    )

def register_handlers_common(dp: Dispatcher):
    dp.register_message_handler(cmd_start, commands="start")

```

Как здесь вызвать метод bot.get_chat_member ?
или какой есть путь, чтобы выполнять данный метод при срабатывании хендлера?

PS: Отличный туторриаль :+1:

**Comment by ANAT01** [comment]
Нашел

```python
from aiogram import Bot,

...
bot = Bot.get_current()
...
```

**Comment by MasterGroosha** [comment]
Это не самый лучший способ. `bot` можно достать прямо из message:

`chat_member = await message.bot.get_chat_member(...)`
