### ISSUE TITLE
Callback handler в food.py

### ISSUE THREAD

**Issue by Cere6ellum** [MasterGroosha/telegram-tutorial-2#9]
А как зарегистрировать dp.callback_query_handler() в food.py ?
Пытался сделать так:
```
async def any_func(call: types.CallbackQuery, message: types.Message):
    await message.answer("callback for " + call.data)

def register_handlers_food(dp: Dispatcher):
    dp.register_message_handler(food_start, commands="food", state="*")
    dp.register_message_handler(food_chosen, state=OrderFood.waiting_for_food_name)
    dp.register_message_handler(food_size_chosen, state=OrderFood.waiting_for_food_size)

    #Вот тут добавил хендлер
    dp.callback_query_handler(lambda c: c.data.startswith("something"))
```

...не работает.

**Comment by MasterGroosha** [comment]
> dp.callback_query_handler(lambda c: c.data.startswith("something"))

Первым аргументом должна идти функция, которая будет вызвана. Рассмотрим пример:

`dp.register_message_handler(food_start, commands="food", state="*")`

food_start — функция, которая будет вызвана
`commands="food", state="*"` — фильтры, при равенстве True которых будет вызвана food_start

**Comment by Cere6ellum** [comment]
Я делал так. Не работает. Если правильно понял.
Вот пример. Убрал все States и другие хендлеры для упрощения:

```
async def any_func(call: types.CallbackQuery, message: types.Message):
    await message.answer("callback for " + call.data)

def register_handlers_food(dp: Dispatcher):
    dp.register_message_handler(food_start, commands="food")

    #Вот тут добавил хендлер
    dp.callback_query_handler(any_func, lambda c: c.data.startswith("something"))
```

Прошу прощения, если я задаю максимально глупый вопрос, но только учусь, и мне очень уж понравилось разграничение обработчиков. Этакий аналог include в php.

**Comment by MasterGroosha** [comment]
```
async def any_func(call: types.CallbackQuery, message: types.Message):
    await message.answer("callback for " + call.data)
```
Тут глупость написана, второй аргумент надо убрать. Ответить на сообщение можно как `await call.message.answer(...)`

`dp.callback_query_handler(any_func, lambda c: c.data.startswith("something"))`
Тут правильно (лямбду можно на что-то ещё заменить, но пока сойдёт)

**Comment by Cere6ellum** [comment]
Да, уже привёл к правильному виду:

```
async def any_func(call: types.CallbackQuery):
    await call.message.answer("callback for " + call.data)
    # Не забываем отчитаться о получении колбэка
    await call.answer()

def register_handlers_food(dp: Dispatcher):
    dp.register_message_handler(food_start, commands="food")

    #Вот тут добавил хендлер
    dp.callback_query_handler(any_func, lambda c: c.data.startswith("something"))
```

Но код не работает.
Ни ошибок, ничего. Тишина.
Пересмотрел уже кучу подобных типовых проектов на aiogram.
Нигде нет варианта с колбек хендлером.

**Comment by MasterGroosha** [comment]
> Ни ошибок, ничего. Тишина.

Такого попросту быть не может. Рекомендую сделать минимально воспроизводимый пример (однофайловый), залить его на gist.github.com и скинуть ссылку здесь в комментариях.

Справка: [что такое минимальный воспроизводимый пример?](https://ru.stackoverflow.com/help/minimal-reproducible-example)

**Comment by MasterGroosha** [comment]
> Нигде нет варианта с колбек хендлером.

Строятся эти примеры точно так же, как и с хэндлерами на обычные сообщения.

**Comment by Cere6ellum** [comment]
Создал на Gist файлик.
Реально не вижу в чём причина отсутствия колбэк-действий. Не работает.
Только нужно вставить токен от своего (любого) бота

[](https://gist.github.com/Cere6ellum/ff7a72e7fc12a41b6d29e7f6ebfe758c)

**Comment by MasterGroosha** [comment]
@Cere6ellum 

```diff
- dp.callback_query_handler(ask_result, lambda c: c.data.startswith("ask_"))
+ dp.register_callback_query_handler(ask_result, lambda c: c.data.startswith("ask_"))
```

**Comment by Cere6ellum** [comment]
Блиииин. А вчера ведь задавался вопросом, почему в случае с message_handler есть префикс register, а здесь нет. Даже пошёл библиотеку Dispatcher ковырять. На пол пути свернул не туда, и забыл. :)
Спасибо огромное. Побежал кодить. Ура.
